# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/po524/Documents/sample1/HandsOn2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/po524/Documents/sample1/HandsOn2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/po524/Documents/sample1/HandsOn2/CMakeFiles /home/po524/Documents/sample1/HandsOn2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/po524/Documents/sample1/HandsOn2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tutorial

# Build rule for target.
Tutorial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Tutorial
.PHONY : Tutorial

# fast build rule for target.
Tutorial/fast:
	$(MAKE) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/build
.PHONY : Tutorial/fast

#=============================================================================
# Target rules for targets named SLACtut

# Build rule for target.
SLACtut: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SLACtut
.PHONY : SLACtut

# fast build rule for target.
SLACtut/fast:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/build
.PHONY : SLACtut/fast

src/ActionInitialization.o: src/ActionInitialization.cc.o

.PHONY : src/ActionInitialization.o

# target to build an object file
src/ActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/ActionInitialization.cc.o
.PHONY : src/ActionInitialization.cc.o

src/ActionInitialization.i: src/ActionInitialization.cc.i

.PHONY : src/ActionInitialization.i

# target to preprocess a source file
src/ActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/ActionInitialization.cc.i
.PHONY : src/ActionInitialization.cc.i

src/ActionInitialization.s: src/ActionInitialization.cc.s

.PHONY : src/ActionInitialization.s

# target to generate assembly for a file
src/ActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/ActionInitialization.cc.s
.PHONY : src/ActionInitialization.cc.s

src/DetectorConstruction.o: src/DetectorConstruction.cc.o

.PHONY : src/DetectorConstruction.o

# target to build an object file
src/DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.cc.o

src/DetectorConstruction.i: src/DetectorConstruction.cc.i

.PHONY : src/DetectorConstruction.i

# target to preprocess a source file
src/DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.cc.i

src/DetectorConstruction.s: src/DetectorConstruction.cc.s

.PHONY : src/DetectorConstruction.s

# target to generate assembly for a file
src/DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.cc.s

src/EventAction.o: src/EventAction.cc.o

.PHONY : src/EventAction.o

# target to build an object file
src/EventAction.cc.o:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/EventAction.cc.o
.PHONY : src/EventAction.cc.o

src/EventAction.i: src/EventAction.cc.i

.PHONY : src/EventAction.i

# target to preprocess a source file
src/EventAction.cc.i:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/EventAction.cc.i
.PHONY : src/EventAction.cc.i

src/EventAction.s: src/EventAction.cc.s

.PHONY : src/EventAction.s

# target to generate assembly for a file
src/EventAction.cc.s:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/EventAction.cc.s
.PHONY : src/EventAction.cc.s

src/Hit.o: src/Hit.cc.o

.PHONY : src/Hit.o

# target to build an object file
src/Hit.cc.o:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/Hit.cc.o
.PHONY : src/Hit.cc.o

src/Hit.i: src/Hit.cc.i

.PHONY : src/Hit.i

# target to preprocess a source file
src/Hit.cc.i:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/Hit.cc.i
.PHONY : src/Hit.cc.i

src/Hit.s: src/Hit.cc.s

.PHONY : src/Hit.s

# target to generate assembly for a file
src/Hit.cc.s:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/Hit.cc.s
.PHONY : src/Hit.cc.s

src/PhysicsList.o: src/PhysicsList.cc.o

.PHONY : src/PhysicsList.o

# target to build an object file
src/PhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/PhysicsList.cc.o
.PHONY : src/PhysicsList.cc.o

src/PhysicsList.i: src/PhysicsList.cc.i

.PHONY : src/PhysicsList.i

# target to preprocess a source file
src/PhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/PhysicsList.cc.i
.PHONY : src/PhysicsList.cc.i

src/PhysicsList.s: src/PhysicsList.cc.s

.PHONY : src/PhysicsList.s

# target to generate assembly for a file
src/PhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/PhysicsList.cc.s
.PHONY : src/PhysicsList.cc.s

src/PrimaryGeneratorAction.o: src/PrimaryGeneratorAction.cc.o

.PHONY : src/PrimaryGeneratorAction.o

# target to build an object file
src/PrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.cc.o

src/PrimaryGeneratorAction.i: src/PrimaryGeneratorAction.cc.i

.PHONY : src/PrimaryGeneratorAction.i

# target to preprocess a source file
src/PrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.cc.i

src/PrimaryGeneratorAction.s: src/PrimaryGeneratorAction.cc.s

.PHONY : src/PrimaryGeneratorAction.s

# target to generate assembly for a file
src/PrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.cc.s

src/PrimaryGeneratorAction__OLD.o: src/PrimaryGeneratorAction__OLD.cc.o

.PHONY : src/PrimaryGeneratorAction__OLD.o

# target to build an object file
src/PrimaryGeneratorAction__OLD.cc.o:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/PrimaryGeneratorAction__OLD.cc.o
.PHONY : src/PrimaryGeneratorAction__OLD.cc.o

src/PrimaryGeneratorAction__OLD.i: src/PrimaryGeneratorAction__OLD.cc.i

.PHONY : src/PrimaryGeneratorAction__OLD.i

# target to preprocess a source file
src/PrimaryGeneratorAction__OLD.cc.i:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/PrimaryGeneratorAction__OLD.cc.i
.PHONY : src/PrimaryGeneratorAction__OLD.cc.i

src/PrimaryGeneratorAction__OLD.s: src/PrimaryGeneratorAction__OLD.cc.s

.PHONY : src/PrimaryGeneratorAction__OLD.s

# target to generate assembly for a file
src/PrimaryGeneratorAction__OLD.cc.s:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/PrimaryGeneratorAction__OLD.cc.s
.PHONY : src/PrimaryGeneratorAction__OLD.cc.s

src/SD.o: src/SD.cc.o

.PHONY : src/SD.o

# target to build an object file
src/SD.cc.o:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/SD.cc.o
.PHONY : src/SD.cc.o

src/SD.i: src/SD.cc.i

.PHONY : src/SD.i

# target to preprocess a source file
src/SD.cc.i:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/SD.cc.i
.PHONY : src/SD.cc.i

src/SD.s: src/SD.cc.s

.PHONY : src/SD.s

# target to generate assembly for a file
src/SD.cc.s:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/src/SD.cc.s
.PHONY : src/SD.cc.s

tutorial.o: tutorial.cc.o

.PHONY : tutorial.o

# target to build an object file
tutorial.cc.o:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/tutorial.cc.o
.PHONY : tutorial.cc.o

tutorial.i: tutorial.cc.i

.PHONY : tutorial.i

# target to preprocess a source file
tutorial.cc.i:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/tutorial.cc.i
.PHONY : tutorial.cc.i

tutorial.s: tutorial.cc.s

.PHONY : tutorial.s

# target to generate assembly for a file
tutorial.cc.s:
	$(MAKE) -f CMakeFiles/SLACtut.dir/build.make CMakeFiles/SLACtut.dir/tutorial.cc.s
.PHONY : tutorial.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... Tutorial"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SLACtut"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... src/ActionInitialization.o"
	@echo "... src/ActionInitialization.i"
	@echo "... src/ActionInitialization.s"
	@echo "... src/DetectorConstruction.o"
	@echo "... src/DetectorConstruction.i"
	@echo "... src/DetectorConstruction.s"
	@echo "... src/EventAction.o"
	@echo "... src/EventAction.i"
	@echo "... src/EventAction.s"
	@echo "... src/Hit.o"
	@echo "... src/Hit.i"
	@echo "... src/Hit.s"
	@echo "... src/PhysicsList.o"
	@echo "... src/PhysicsList.i"
	@echo "... src/PhysicsList.s"
	@echo "... src/PrimaryGeneratorAction.o"
	@echo "... src/PrimaryGeneratorAction.i"
	@echo "... src/PrimaryGeneratorAction.s"
	@echo "... src/PrimaryGeneratorAction__OLD.o"
	@echo "... src/PrimaryGeneratorAction__OLD.i"
	@echo "... src/PrimaryGeneratorAction__OLD.s"
	@echo "... src/SD.o"
	@echo "... src/SD.i"
	@echo "... src/SD.s"
	@echo "... tutorial.o"
	@echo "... tutorial.i"
	@echo "... tutorial.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

